GIT_COMMAND_LIST = [
    'add', 'am', 'annotate', 'apply', 'archimport',
    'archive', 'bisect', 'bisect--helper', 'blame', 'branch', 'bundle',
    'cat-file', 'check-attr', 'check-ignore', 'check-mailmap',
    'check-ref-format', 'checkout', 'checkout-index', 'cherry', 'cherry-pick',
    'citool', 'clean', 'clone', 'column', 'commit', 'commit-tree', 'config',
    'count-objects', 'credential', 'credential-cache',
    'credential-cache--daemon', 'credential-osxkeychain', 'credential-store',
    'cvsexportcommit', 'cvsimport', 'cvsserver', 'daemon', 'describe',
    'diff', 'diff-files', 'diff-index', 'diff-tree', 'difftool',
    'difftool--helper', 'fast-export', 'fast-import', 'fetch',
    'filter-branch', 'fmt-merge-msg', 'for-each-ref', 'format-patch',
    'fsck', 'fsck-objects', 'gc', 'grep',
    'gui--askpass', 'hash-object', 'help', 'http-backend', 'http-fetch',
    'http-push', 'imap-send', 'index-pack', 'init', 'init-db', 'instaweb',
    'interpret-trailers', 'log', 'ls-files', 'ls-remote', 'ls-tree',
    'mailinfo', 'mailsplit', 'merge', 'merge-base', 'merge-file',
    'merge-index', 'merge-octopus', 'merge-one-file', 'merge-ours',
    'merge-recursive', 'merge-resolve', 'merge-subtree', 'merge-tree',
    'mergetool', 'mergetool--lib', 'mktag', 'mktree', 'mv', 'name-rev',
    'notes', 'p4', 'pack-objects', 'pack-redundant', 'pack-refs',
    'parse-remote', 'patch-id', 'prune', 'prune-packed', 'pull', 'push',
    'quiltimport', 'read-tree', 'rebase', 'rebase--am',
    'rebase--merge', 'receive-pack', 'reflog', 'relink', 'remote',
    'repack', 'replace', 'request-pull',
    'rerere', 'reset', 'rev-list', 'rev-parse', 'revert', 'rm', 'send-email',
    'send-pack', 'sh-i18n', 'sh-i18n--envsubst', 'sh-setup', 'shell',
    'shortlog', 'show', 'show-branch', 'show-index', 'show-ref', 'stage',
    'stash', 'status', 'stripspace', 'submodule', 'submodule--helper',
    'subtree', 'svn', 'symbolic-ref', 'tag', 'unpack-file', 'unpack-objects',
    'update-index', 'update-ref', 'update-server-info', 'upload-archive',
    'upload-pack', 'var', 'verify-commit', 'verify-pack', 'verify-tag',
    'web--browse', 'whatchanged', 'worktree', 'write-tree',
]

GIT_COMMAND_DASHES = {
 'add': {'--ignore-errors',
         '--ignore-missing',
         '--no-all',
         '--refresh',
         '-A',
         '-N',
         '-e',
         '-f',
         '-i',
         '-n',
         '-p',
         '-u',
         '-v'},
 'am': {'--abort',
        '--committer-date-is-author-date',
        '--continue',
        '--directory=',
        '--ignore-date',
        '--ignore-space-change',
        '--keep-non-patch',
        '--no-',
        '--no-message-id',
        '--no-scissors',
        '--no-utf',
        '--patch-format',
        '--resolvemsg=',
        '--skip',
        '-S',
        '-c',
        '-i',
        '-k',
        '-m',
        '-q',
        '-s',
        '-u'},
 'annotate': {'--contents',
              '--date',
              '--encoding=',
              '--incremental',
              '--line-porcelain',
              '--reverse',
              '--root',
              '--show-stats',
              '-C',
              '-L',
              '-M',
              '-S',
              '-b',
              '-h',
              '-l',
              '-p',
              '-t'},
 'apply': {'--allow-binary-replacement',
           '--apply',
           '--build-fake-ancestor=',
           '--cached',
           '--check',
           '--directory=',
           '--exclude=',
           '--ignore-space-change',
           '--inaccurate-eof',
           '--include=',
           '--index',
           '--no-add',
           '--numstat',
           '--recount',
           '--reject',
           '--stat',
           '--summary',
           '--unidiff-zero',
           '--unsafe-paths',
           '--whitespace=',
           '-C',
           '-R',
           '-p',
           '-v',
           '-z'},
 'archimport': {'-f', '-a', '-v', '-h', '-D', '-o', '-T', '-t'},
 'archive': {'--exec=',
             '--format=',
             '--prefix=',
             '--remote',
             '--remote=',
             '--worktree-attributes',
             '-l',
             '-o',
             '-v'},
 'bisect': {'--no-checkout'},
 'bisect--helper': set(),
 'blame': {'--abbrev=',
           '--contents',
           '--date',
           '--encoding=',
           '--incremental',
           '--line-porcelain',
           '--reverse',
           '--root',
           '--score-debug',
           '--show-stats',
           '-C',
           '-L',
           '-M',
           '-S',
           '-b',
           '-c',
           '-e',
           '-f',
           '-h',
           '-l',
           '-n',
           '-p',
           '-s',
           '-t',
           '-w'},
 'br': {'--abbrev=',
        '--color',
        '--column',
        '--contains',
        '--edit-description',
        '--list',
        '--merged',
        '--move',
        '--no-abbrev',
        '--no-color',
        '--no-merged',
        '--no-track',
        '--points-at',
        '--set-upstream',
        '--set-upstream-to',
        '--sort=',
        '--track',
        '--unset-upstream',
        '-D',
        '-M',
        '-a',
        '-d',
        '-f',
        '-l',
        '-m',
        '-q',
        '-r',
        '-t',
        '-u',
        '-v'},
 'branch': {'--abbrev=',
            '--color',
            '--column',
            '--contains',
            '--edit-description',
            '--list',
            '--merged',
            '--move',
            '--no-abbrev',
            '--no-color',
            '--no-merged',
            '--no-track',
            '--points-at',
            '--set-upstream',
            '--set-upstream-to',
            '--sort=',
            '--track',
            '--unset-upstream',
            '-D',
            '-M',
            '-a',
            '-d',
            '-f',
            '-l',
            '-m',
            '-q',
            '-r',
            '-t',
            '-u',
            '-v'},
 'bundle': set(),
 'cat-file': {'--allow-unknown-type',
              '--batch',
              '--batch-all-objects',
              '--batch-check',
              '--buffer',
              '--follow-symlinks',
              '--textconv',
              '-e',
              '-p',
              '-s',
              '-t'},
 'check-attr': {'-z', '-a', '--stdin', '--cached'},
 'check-ignore': {'--stdin',
                  '-v',
                  '--no-index',
                  '--verbose',
                  '-n',
                  '-z',
                  '-q'},
 'check-mailmap': {'--stdin'},
 'check-ref-format': {'--normalize', '--refspec-pattern'},
 'checkout': {'--conflict=',
              '--detach',
              '--ignore-other-worktrees',
              '--ignore-skip-worktree-bits',
              '--no-track',
              '--orphan',
              '--ours',
              '-B',
              '-b',
              '-f',
              '-l',
              '-m',
              '-p',
              '-q',
              '-t'},
 'checkout-index': {'--prefix=',
                    '--stage=',
                    '--stdin',
                    '--temp',
                    '-a',
                    '-f',
                    '-n',
                    '-q',
                    '-u',
                    '-z'},
 'cherry': {'-v'},
 'cherry-pick': {'--abort',
                 '--allow-empty',
                 '--allow-empty-message',
                 '--continue',
                 '--ff',
                 '--keep-redundant-commits',
                 '--quit',
                 '--strategy=',
                 '-S',
                 '-X',
                 '-e',
                 '-m',
                 '-n',
                 '-r',
                 '-s',
                 '-x'},
 'ci': {'--allow-empty',
        '--allow-empty-message',
        '--amend',
        '--author=',
        '--branch',
        '--cleanup=',
        '--date=',
        '--dry-run',
        '--fixup=',
        '--long',
        '--no-edit',
        '--no-gpg-sign',
        '--no-post-rewrite',
        '--no-status',
        '--porcelain',
        '--reset-author',
        '--short',
        '--squash=',
        '--status',
        '-C',
        '-F',
        '-S',
        '-a',
        '-c',
        '-e',
        '-i',
        '-m',
        '-n',
        '-o',
        '-p',
        '-q',
        '-s',
        '-t',
        '-u',
        '-v',
        '-z'},
 'citool': set(),
 'clean': {'-f', '-i', '-X', '-e', '-n', '-d', '-x', '-q'},
 'clone': {'--auto',
           '--bare',
           '--branch',
           '--config',
           '--depth',
           '--dissociate',
           '--local',
           '--mirror',
           '--no-checkout',
           '--no-hardlinks',
           '--no-local',
           '--origin',
           '--progress',
           '--quiet',
           '--recursive',
           '--reference',
           '--separate-git-dir=',
           '--shared',
           '--single-branch',
           '--template=',
           '--upload-pack',
           '--verbose',
           '-l'},
 'co': {'--conflict=',
        '--detach',
        '--ignore-other-worktrees',
        '--ignore-skip-worktree-bits',
        '--no-track',
        '--orphan',
        '--ours',
        '-B',
        '-b',
        '-f',
        '-l',
        '-m',
        '-p',
        '-q',
        '-t'},
 'column': {'--command=',
            '--indent=',
            '--mode=',
            '--nl=',
            '--padding=',
            '--raw-mode=',
            '--width='},
 'commit': {'--allow-empty',
            '--allow-empty-message',
            '--amend',
            '--author=',
            '--branch',
            '--cleanup=',
            '--date=',
            '--dry-run',
            '--fixup=',
            '--long',
            '--no-edit',
            '--no-gpg-sign',
            '--no-post-rewrite',
            '--no-status',
            '--porcelain',
            '--reset-author',
            '--short',
            '--squash=',
            '--status',
            '-C',
            '-F',
            '-S',
            '-a',
            '-c',
            '-e',
            '-i',
            '-m',
            '-n',
            '-o',
            '-p',
            '-q',
            '-s',
            '-t',
            '-u',
            '-v',
            '-z'},
 'commit-tree': {'-m', '-S', '--no-gpg-sign', '-p', '-F'},
 'config': {'--add',
            '--auto',
            '--blob',
            '--bool',
            '--bool-or-int',
            '--cc',
            '--dirstat',
            '--ff-only',
            '--get',
            '--get-all',
            '--get-color',
            '--get-colorbool',
            '--get-regexp',
            '--get-urlmatch',
            '--global',
            '--int',
            '--local',
            '--name-only',
            '--output',
            '--path',
            '--pretty=',
            '--quiet',
            '--receive-pack',
            '--remove-section',
            '--rename-section',
            '--replace-all',
            '--scissors',
            '--system',
            '--unset',
            '--unset-all',
            '--upload-pack',
            '-e',
            '-f',
            '-l',
            '-z'},
 'count-objects': {'-v', '-H'},
 'credential': set(),
 'credential-cache': {'--timeout', '--socket'},
 'credential-cache--daemon': set(),
 'credential-osxkeychain': set(),
 'credential-store': {'--file='},
 'cvsexportcommit': {'-P',
                     '-W',
                     '-a',
                     '-c',
                     '-d',
                     '-f',
                     '-k',
                     '-m',
                     '-p',
                     '-u',
                     '-v',
                     '-w'},
 'cvsimport': {'-A',
               '-C',
               '-L',
               '-M',
               '-P',
               '-R',
               '-S',
               '-a',
               '-d',
               '-h',
               '-i',
               '-k',
               '-m',
               '-o',
               '-p',
               '-r',
               '-s',
               '-u',
               '-v',
               '-z'},
 'cvsserver': {'--export-all', '--strict-paths', '-V', '--base-path', '-h'},
 'daemon': {'--access-hook=',
            '--allow-override=',
            '--base-path',
            '--base-path-relaxed',
            '--base-path=',
            '--detach',
            '--enable=',
            '--export-all',
            '--inetd',
            '--init-timeout=',
            '--interpolated-path=',
            '--listen=',
            '--max-connections=',
            '--pid-file=',
            '--port',
            '--port=',
            '--reuseaddr',
            '--strict-paths',
            '--syslog',
            '--timeout=',
            '--user-path',
            '--user=',
            '--verbose'},
 'describe': {'--abbrev=',
              '--all',
              '--always',
              '--candidates=',
              '--contains',
              '--debug',
              '--dirty',
              '--exact-match',
              '--first-parent',
              '--long',
              '--match',
              '--tags'},
 'diff': {'--abbrev',
          '--binary',
          '--cached',
          '--check',
          '--color',
          '--color-words',
          '--diff-algorithm=',
          '--diff-filter=',
          '--dirstat',
          '--dst-prefix=',
          '--exit-code',
          '--ext-diff',
          '--find-copies-harder',
          '--full-index',
          '--histogram',
          '--ignore-blank-lines',
          '--ignore-space-at-eol',
          '--ignore-submodules',
          '--inter-hunk-context=',
          '--minimal',
          '--name-only',
          '--name-status',
          '--no-color',
          '--no-ext-diff',
          '--no-index',
          '--no-prefix',
          '--no-renames',
          '--numstat',
          '--patch-with-raw',
          '--patch-with-stat',
          '--patience',
          '--pickaxe-all',
          '--pickaxe-regex',
          '--quiet',
          '--raw',
          '--relative',
          '--shortstat',
          '--src-prefix=',
          '--stat',
          '--stat-name-width=',
          '--submodule',
          '--submodule=',
          '--summary',
          '--textconv',
          '--word-diff',
          '--word-diff-regex=',
          '--ws-error-highlight=',
          '-B',
          '-C',
          '-D',
          '-G',
          '-M',
          '-O',
          '-R',
          '-S',
          '-U',
          '-W',
          '-a',
          '-b',
          '-l',
          '-p',
          '-s',
          '-static',
          '-w',
          '-z'},
 'diff-files': {'--abbrev',
                '--binary',
                '--check',
                '--color',
                '--color-words',
                '--diff-algorithm=',
                '--diff-filter=',
                '--dirstat',
                '--dst-prefix=',
                '--exit-code',
                '--ext-diff',
                '--find-copies-harder',
                '--full-index',
                '--histogram',
                '--ignore-blank-lines',
                '--ignore-space-at-eol',
                '--ignore-submodules',
                '--inter-hunk-context=',
                '--minimal',
                '--name-only',
                '--name-status',
                '--no-color',
                '--no-ext-diff',
                '--no-prefix',
                '--no-renames',
                '--numstat',
                '--patch-with-raw',
                '--patch-with-stat',
                '--patience',
                '--pickaxe-all',
                '--pickaxe-regex',
                '--quiet',
                '--raw',
                '--relative',
                '--shortstat',
                '--src-prefix=',
                '--stat',
                '--stat-name-width=',
                '--submodule',
                '--submodule=',
                '--summary',
                '--textconv',
                '--word-diff',
                '--word-diff-regex=',
                '--ws-error-highlight=',
                '-B',
                '-C',
                '-D',
                '-G',
                '-M',
                '-O',
                '-R',
                '-S',
                '-U',
                '-W',
                '-a',
                '-b',
                '-c',
                '-l',
                '-p',
                '-q',
                '-s',
                '-static',
                '-w',
                '-z'},
 'diff-index': {'--abbrev',
                '--binary',
                '--cached',
                '--check',
                '--color',
                '--color-words',
                '--diff-algorithm=',
                '--diff-filter=',
                '--dirstat',
                '--dst-prefix=',
                '--exit-code',
                '--ext-diff',
                '--find-copies-harder',
                '--full-index',
                '--histogram',
                '--ignore-blank-lines',
                '--ignore-space-at-eol',
                '--ignore-submodules',
                '--inter-hunk-context=',
                '--minimal',
                '--name-only',
                '--name-status',
                '--no-color',
                '--no-ext-diff',
                '--no-prefix',
                '--no-renames',
                '--numstat',
                '--patch-with-raw',
                '--patch-with-stat',
                '--patience',
                '--pickaxe-all',
                '--pickaxe-regex',
                '--quiet',
                '--raw',
                '--relative',
                '--shortstat',
                '--src-prefix=',
                '--stat',
                '--stat-name-width=',
                '--submodule',
                '--submodule=',
                '--summary',
                '--textconv',
                '--word-diff',
                '--word-diff-regex=',
                '--ws-error-highlight=',
                '-B',
                '-C',
                '-D',
                '-G',
                '-M',
                '-O',
                '-R',
                '-S',
                '-U',
                '-W',
                '-a',
                '-b',
                '-l',
                '-m',
                '-p',
                '-s',
                '-static',
                '-w',
                '-z'},
 'diff-tree': {'--abbrev',
               '--abbrev-commit',
               '--always',
               '--binary',
               '--cc',
               '--check',
               '--color',
               '--color-words',
               '--diff-algorithm=',
               '--diff-filter=',
               '--dirstat',
               '--dst-prefix=',
               '--encoding=',
               '--exit-code',
               '--ext-diff',
               '--find-copies-harder',
               '--full-index',
               '--histogram',
               '--ignore-blank-lines',
               '--ignore-space-at-eol',
               '--ignore-submodules',
               '--inter-hunk-context=',
               '--minimal',
               '--name-only',
               '--name-status',
               '--no-abbrev-commit',
               '--no-color',
               '--no-commit-id',
               '--no-ext-diff',
               '--no-notes',
               '--no-prefix',
               '--no-renames',
               '--notes',
               '--numstat',
               '--oneline',
               '--patch-with-raw',
               '--patch-with-stat',
               '--patience',
               '--pickaxe-all',
               '--pickaxe-regex',
               '--pretty',
               '--quiet',
               '--raw',
               '--relative',
               '--root',
               '--shortstat',
               '--show-notes',
               '--show-signature',
               '--src-prefix=',
               '--stat',
               '--stat-name-width=',
               '--stdin',
               '--submodule',
               '--submodule=',
               '--summary',
               '--textconv',
               '--word-diff',
               '--word-diff-regex=',
               '--ws-error-highlight=',
               '-B',
               '-C',
               '-D',
               '-G',
               '-M',
               '-O',
               '-R',
               '-S',
               '-U',
               '-W',
               '-a',
               '-b',
               '-c',
               '-l',
               '-m',
               '-p',
               '-r',
               '-s',
               '-static',
               '-t',
               '-v',
               '-w',
               '-z'},
 'difftool': {'--dir-diff',
              '--prompt',
              '--tool-help',
              '-d',
              '-g',
              '-t',
              '-x',
              '-y'},
 'difftool--helper': set(),
 'fast-export': {'--anonymize',
                 '--export-marks=',
                 '--fake-missing-tagger',
                 '--full-tree',
                 '--import-marks=',
                 '--no-data',
                 '--progress=',
                 '--refspec',
                 '--signed-tags=',
                 '--tag-of-filtered-object=',
                 '--use-done-feature',
                 '-M'},
 'fast-import': {'--active-branches=',
                 '--big-file-threshold=',
                 '--cat-blob-fd',
                 '--cat-blob-fd=',
                 '--date-format=',
                 '--depth=',
                 '--done',
                 '--export-marks',
                 '--export-marks=',
                 '--export-pack-edges=',
                 '--force',
                 '--import-marks',
                 '--import-marks-if-exists=',
                 '--import-marks=',
                 '--max-pack-size',
                 '--max-pack-size=',
                 '--quiet',
                 '--stats',
                 '-a',
                 '-d'},
 'fetch': {'--all',
           '--depth=',
           '--dry-run',
           '--local',
           '--multiple',
           '--no-recurse-submodules',
           '--progress',
           '--recurse-submodules',
           '--recurse-submodules-default=',
           '--refmap=',
           '--submodule-prefix=',
           '--unshallow',
           '--update-shallow',
           '--upload-pack',
           '-a',
           '-f',
           '-k',
           '-n',
           '-p',
           '-q',
           '-t',
           '-u',
           '-v'},
 'filter-branch': {'--commit-filter',
                   '--env-filter',
                   '--format=',
                   '--ignore-unmatch',
                   '--index-filter',
                   '--msg-filter',
                   '--original',
                   '--parent-filter',
                   '--prune-empty',
                   '--subdirectory-filter',
                   '--tag-name-filter',
                   '--tree-filter',
                   '-d',
                   '-f'},
 'fmt-merge-msg': {'-m', '--no-log', '-F', '--log'},
 'for-each-ref': {'--contains',
                  '--format=',
                  '--merged',
                  '--no-merged',
                  '--points-at',
                  '--shell',
                  '--sort='},
 'format-patch': {'--abbrev',
                  '--add-header=',
                  '--attach',
                  '--binary',
                  '--cc=',
                  '--diff-algorithm=',
                  '--dirstat',
                  '--dst-prefix=',
                  '--ext-diff',
                  '--find-copies-harder',
                  '--from',
                  '--full-index',
                  '--histogram',
                  '--ignore-blank-lines',
                  '--ignore-if-in-upstream',
                  '--ignore-space-at-eol',
                  '--ignore-submodules',
                  '--in-reply-to=',
                  '--inline',
                  '--inter-hunk-context=',
                  '--minimal',
                  '--no-attach',
                  '--no-binary',
                  '--no-ext-diff',
                  '--no-prefix',
                  '--no-renames',
                  '--notes',
                  '--numbered-files',
                  '--numstat',
                  '--patience',
                  '--root',
                  '--shortstat',
                  '--signature-file=',
                  '--src-prefix=',
                  '--start-number',
                  '--stat',
                  '--stat-name-width=',
                  '--stdout',
                  '--subject-prefix',
                  '--subject-prefix=',
                  '--suffix=',
                  '--summary',
                  '--textconv',
                  '--thread',
                  '--to=',
                  '--zero-commit',
                  '-B',
                  '-C',
                  '-D',
                  '-M',
                  '-N',
                  '-O',
                  '-U',
                  '-W',
                  '-a',
                  '-b',
                  '-k',
                  '-l',
                  '-n',
                  '-o',
                  '-p',
                  '-q',
                  '-s',
                  '-v',
                  '-w'},
 'fsck': {'--cache',
          '--connectivity-only',
          '--full',
          '--lost-found',
          '--no-reflogs',
          '--root',
          '--strict',
          '--tags',
          '--unreachable',
          '--verbose'},
 'fsck-objects': set(),
 'gc': {'--aggressive',
        '--auto',
        '--force',
        '--no-prune',
        '--prune=',
        '--quiet',
        '-A'},
 'grep': {'--all-match',
          '--and',
          '--break',
          '--cached',
          '--color',
          '--exclude-standard',
          '--full-name',
          '--heading',
          '--max-depth',
          '--no-color',
          '--no-exclude-standard',
          '--no-index',
          '--no-textconv',
          '--textconv',
          '--untracked',
          '-A',
          '-B',
          '-E',
          '-F',
          '-I',
          '-O',
          '-P',
          '-W',
          '-a',
          '-c',
          '-e',
          '-f',
          '-h',
          '-i',
          '-l',
          '-n',
          '-p',
          '-q',
          '-v',
          '-w',
          '-z'},
 'gui--askpass': set(),
 'hash-object': {'--literally',
                 '--no-filters',
                 '--path',
                 '--stdin',
                 '--stdin-paths',
                 '-t',
                 '-w'},
 'help': {'-i', '-m', '-g', '-a', '-w'},
 'http-backend': set(),
 'http-fetch': {'-a', '--stdin', '-v', '-c', '-w', '--recover', '-t'},
 'http-push': {'-d', '--dry-run', '--verbose', '--force', '--all'},
 'imap-send': {'--curl', '--no-curl', '-v', '-q'},
 'index-pack': {'--check-self-contained-and-connected',
                '--fix-thin',
                '--index-version=',
                '--keep',
                '--keep=',
                '--stdin',
                '--strict',
                '--threads=',
                '-o',
                '-v'},
 'init': {'--shared', '--template=', '--separate-git-dir=', '--bare', '-q'},
 'init-db': set(),
 'instaweb': {'-b', '-m', '-d', '-l', '-p'},
 'interpret-trailers': {'--trim-empty', '--trailer'},
 'log': {'--abbrev',
         '--abbrev-commit',
         '--all',
         '--all-match',
         '--ancestry-path',
         '--author-date-order',
         '--author=',
         '--basic-regexp',
         '--binary',
         '--bisect',
         '--boundary',
         '--branches',
         '--cc',
         '--check',
         '--cherry',
         '--cherry-mark',
         '--cherry-pick',
         '--children',
         '--color',
         '--color-words',
         '--committer=',
         '--date-order',
         '--date=',
         '--dense',
         '--diff-algorithm=',
         '--diff-filter=',
         '--dirstat',
         '--do-walk',
         '--dst-prefix=',
         '--encoding=',
         '--exclude=',
         '--exit-code',
         '--ext-diff',
         '--find-copies-harder',
         '--first-parent',
         '--follow',
         '--full-diff',
         '--full-history',
         '--full-index',
         '--glob=',
         '--graph',
         '--grep-reflog=',
         '--grep=',
         '--histogram',
         '--ignore-blank-lines',
         '--ignore-missing',
         '--ignore-space-at-eol',
         '--ignore-submodules',
         '--inter-hunk-context=',
         '--invert-grep',
         '--left-only',
         '--left-right',
         '--log-size',
         '--max-parents=',
         '--merge',
         '--merges',
         '--min-parents=',
         '--minimal',
         '--name-only',
         '--name-status',
         '--no-abbrev-commit',
         '--no-color',
         '--no-decorate',
         '--no-ext-diff',
         '--no-merges',
         '--no-min-parents',
         '--no-notes',
         '--no-prefix',
         '--no-renames',
         '--no-walk',
         '--not',
         '--notes',
         '--numstat',
         '--oneline',
         '--parents',
         '--patch-with-raw',
         '--patch-with-stat',
         '--patience',
         '--perl-regexp',
         '--pickaxe-all',
         '--pickaxe-regex',
         '--pretty',
         '--raw',
         '--reflog',
         '--relative',
         '--relative-date',
         '--remotes',
         '--remove-empty',
         '--reverse',
         '--shortstat',
         '--show-linear-break',
         '--show-notes',
         '--show-signature',
         '--simplify-by-decoration',
         '--simplify-merges',
         '--since=',
         '--skip=',
         '--source',
         '--sparse',
         '--src-prefix=',
         '--stat',
         '--stat-name-width=',
         '--stdin',
         '--submodule',
         '--submodule=',
         '--summary',
         '--tags',
         '--textconv',
         '--topo-order',
         '--until=',
         '--use-mailmap',
         '--walk-reflogs',
         '--word-diff',
         '--word-diff-regex=',
         '--ws-error-highlight=',
         '-B',
         '-C',
         '-D',
         '-E',
         '-F',
         '-G',
         '-L',
         '-M',
         '-O',
         '-R',
         '-S',
         '-U',
         '-W',
         '-a',
         '-b',
         '-c',
         '-g',
         '-i',
         '-l',
         '-local',
         '-m',
         '-p',
         '-r',
         '-s',
         '-static',
         '-t',
         '-w',
         '-xxxxxxx',
         '-yyyyyyy',
         '-z'},
 'ls-files': {'--abbrev',
              '--debug',
              '--directory',
              '--error-unmatch',
              '--exclude-from',
              '--exclude-per-directory=',
              '--exclude-standard',
              '--full-name',
              '--no-empty-directory',
              '--with-tree=',
              '-X',
              '-c',
              '-d',
              '-i',
              '-k',
              '-m',
              '-o',
              '-s',
              '-t',
              '-u',
              '-v',
              '-x',
              '-z'},
 'ls-remote': {'--get-url', '--exit-code', '--upload-pack=', '-h'},
 'ls-tree': {'--abbrev',
             '--full-name',
             '--full-tree',
             '--name-only',
             '--stdin',
             '-d',
             '-l',
             '-r',
             '-t',
             '-z'},
 'mailinfo': {'--encoding=',
              '--no-scissors',
              '--scissors',
              '-b',
              '-k',
              '-m',
              '-n',
              '-u'},
 'mailsplit': {'-b', '-d', '-f', '--keep-cr', '-o'},
 'merge': {'--abort',
           '--commit',
           '--edit',
           '--ff',
           '--ff-only',
           '--log',
           '--no-commit',
           '--no-edit',
           '--no-ff',
           '--progress',
           '--squash',
           '--stat',
           '--summary',
           '--verify-signatures',
           '-S',
           '-X',
           '-m',
           '-q',
           '-s',
           '-v'},
 'merge-base': {'---o---',
                '---o---o---B',
                '--fork-point',
                '--independent',
                '--is-ancestor',
                '--octopus',
                '-a'},
 'merge-file': {'--ours', '--diff', '-p', '-L', '-q'},
 'merge-index': {'-o', '-a', '-q'},
 'merge-octopus': set(),
 'merge-one-file': set(),
 'merge-ours': set(),
 'merge-recursive': set(),
 'merge-resolve': set(),
 'merge-subtree': set(),
 'merge-tree': set(),
 'mergetool': {'--prompt', '--tool-help', '-t', '-y'},
 'mergetool--lib': set(),
 'mktag': set(),
 'mktree': {'--batch', '--missing', '-z'},
 'mv': {'-f', '-k', '-v', '-n'},
 'name-rev': {'--all',
              '--always',
              '--name-only',
              '--no-undefined',
              '--refs=',
              '--stdin',
              '--tags'},
 'notes': {'--abort',
           '--allow-empty',
           '--commit',
           '--ignore-missing',
           '--ref',
           '--stdin',
           '-C',
           '-F',
           '-c',
           '-f',
           '-m',
           '-n',
           '-q',
           '-s',
           '-v'},
 'p4': {'--bare',
        '--branch',
        '--changes-block-size',
        '--changesfile',
        '--conflict=',
        '--destination',
        '--detect-branches',
        '--detect-labels',
        '--export-labels',
        '--git-dir',
        '--import-labels',
        '--import-local',
        '--keep-path',
        '--max-changes',
        '--origin',
        '--prepare-p',
        '--preserve-user',
        '--silent',
        '--use-client-spec',
        '-M',
        '-n',
        '-v'},
 'pack-objects': {'--all',
                  '--all-progress',
                  '--all-progress-implied',
                  '--compression=',
                  '--delta-base-offset',
                  '--honor-pack-keep',
                  '--include-tag',
                  '--incremental',
                  '--index-version=',
                  '--keep-true-parents',
                  '--local',
                  '--max-pack-size=',
                  '--no-reuse-delta',
                  '--no-reuse-object',
                  '--non-empty',
                  '--progress',
                  '--revs',
                  '--shallow',
                  '--stdout',
                  '--thin',
                  '--threads=',
                  '--unpacked',
                  '--window-memory=',
                  '--window=',
                  '-q'},
 'pack-redundant': {'--alt-odb', '--verbose', '--all'},
 'pack-refs': {'--no-prune', '--all'},
 'parse-remote': set(),
 'patch-id': {'--unstable', '--stable'},
 'prune': {'--expire', '-v', '-n'},
 'prune-packed': {'-q', '-n'},
 'pull': {'--all',
          '--commit',
          '--depth=',
          '--edit',
          '--ff',
          '--ff-only',
          '--local',
          '--log',
          '--no-commit',
          '--no-edit',
          '--no-ff',
          '--no-rebase',
          '--no-tags',
          '--progress',
          '--squash',
          '--stat',
          '--summary',
          '--unshallow',
          '--update-shallow',
          '--upload-pack',
          '--verify-signatures',
          '-X',
          '-a',
          '-f',
          '-k',
          '-q',
          '-r',
          '-s',
          '-u',
          '-v'},
 'push': {'---X---A',
          '--all',
          '--delete',
          '--follow-tags',
          '--force',
          '--force-with-lease',
          '--force-with-lease=',
          '--local',
          '--mirror',
          '--no-recurse-submodules',
          '--porcelain',
          '--progress',
          '--prune',
          '--rebase',
          '--receive-pack=',
          '--repo=',
          '--tags',
          '-f',
          '-n',
          '-q',
          '-u',
          '-v'},
 'quiltimport': {'--patches', '--series', '--author', '-n'},
 'read-tree': {'--aggressive',
               '--empty',
               '--exclude-per-directory=',
               '--index-output=',
               '--no-sparse-checkout',
               '--prefix=',
               '--reset',
               '--trivial',
               '-a',
               '-i',
               '-m',
               '-n',
               '-u',
               '-v'},
 'rebase': {'---o---O---P---Q',
            '--abort',
            '--autosquash',
            '--autostash',
            '--committer-date-is-author-date',
            '--continue',
            '--edit-todo',
            '--fork-point',
            '--ignore-whitespace',
            '--interactive',
            '--keep-empty',
            '--no-ff',
            '--no-fork-point',
            '--no-verify',
            '--onto',
            '--preserve-merges',
            '--root',
            '--skip',
            '--stat',
            '--verify',
            '-C',
            '-S',
            '-X',
            '-f',
            '-i',
            '-m',
            '-n',
            '-p',
            '-q',
            '-s',
            '-v',
            '-x'},
 'rebase--am': set(),
 'rebase--merge': set(),
 'receive-pack': set(),
 'reflog': {'--all',
            '--expire',
            '--expire-unreachable=',
            '--expire=',
            '--rewrite',
            '--stale-fix',
            '--updateref',
            '--verbose',
            '-n'},
 'relink': {'--safe'},
 'remote': {'--mirror', '-v'},
 'repack': {'--max-pack-size=',
            '--pack-kept-objects',
            '--window-memory=',
            '--window=',
            '-A',
            '-F',
            '-a',
            '-b',
            '-d',
            '-f',
            '-l',
            '-n',
            '-q'},
 'replace': {'--edit',
             '--format=',
             '--graft',
             '--no-replace-objects',
             '--raw',
             '-d',
             '-f',
             '-l'},
 'request-pull': {'-p'},
 'rerere': set(),
 'reset': {'--merge', '--hard', '--mixed', '--keep', '--soft', '-q'},
 'rev-list': {'--abbrev-commit',
              '--all',
              '--all-match',
              '--ancestry-path',
              '--author-date-order',
              '--author=',
              '--basic-regexp',
              '--bisect',
              '--bisect-all',
              '--bisect-vars',
              '--boundary',
              '--branches',
              '--cherry',
              '--cherry-mark',
              '--cherry-pick',
              '--children',
              '--committer=',
              '--count',
              '--date-order',
              '--date=',
              '--dense',
              '--do-walk',
              '--encoding=',
              '--exclude=',
              '--first-parent',
              '--full-history',
              '--glob=',
              '--graph',
              '--grep-reflog=',
              '--grep=',
              '--header',
              '--ignore-missing',
              '--indexed-objects',
              '--invert-grep',
              '--left-only',
              '--left-right',
              '--max-age=',
              '--max-parents=',
              '--merge',
              '--merges',
              '--min-parents=',
              '--no-abbrev-commit',
              '--no-merges',
              '--no-min-parents',
              '--no-walk',
              '--not',
              '--objects',
              '--objects-edge',
              '--objects-edge-aggressive',
              '--oneline',
              '--parents',
              '--perl-regexp',
              '--pretty',
              '--quiet',
              '--reflog',
              '--relative-date',
              '--remotes',
              '--remove-empty',
              '--reverse',
              '--show-linear-break',
              '--show-signature',
              '--simplify-by-decoration',
              '--simplify-merges',
              '--since=',
              '--skip=',
              '--sparse',
              '--stdin',
              '--tags',
              '--timestamp',
              '--topo-order',
              '--unpacked',
              '--until=',
              '--use-bitmap-index',
              '--walk-reflogs',
              '-E',
              '-F',
              '-g',
              '-i',
              '-local',
              '-xxxxxxx',
              '-yyyyyyy'},
 'rev-parse': {'--abbrev-ref',
               '--all',
               '--bar',
               '--baz',
               '--branches',
               '--default',
               '--disambiguate=',
               '--exclude=',
               '--flags',
               '--foo',
               '--git-common-dir',
               '--git-dir',
               '--git-path',
               '--glob=',
               '--is-bare-repository',
               '--is-inside-git-dir',
               '--is-inside-work-tree',
               '--keep-dashdash',
               '--local-env-vars',
               '--no-flags',
               '--no-revs',
               '--not',
               '--parseopt',
               '--prefix',
               '--qux',
               '--remotes',
               '--resolve-git-dir',
               '--revs-only',
               '--shared-index-path',
               '--short',
               '--show-cdup',
               '--show-prefix',
               '--show-toplevel',
               '--since=',
               '--sq',
               '--sq-quote',
               '--stop-at-non-option',
               '--stuck-long',
               '--symbolic',
               '--symbolic-full-name',
               '--until=',
               '--verify',
               '-C',
               '-h',
               '-q'},
 'revert': {'--abort',
            '--continue',
            '--no-edit',
            '--quit',
            '--strategy=',
            '-S',
            '-X',
            '-e',
            '-m',
            '-n',
            '-s'},
 'rm': {'-f', '-r', '--ignore-unmatch', '--cached', '-u', '-n', '-q'},
 'send-email': {'--annotate',
                '--bcc=',
                '--cc-cmd=',
                '--cc=',
                '--compose',
                '--compose-encoding=',
                '--confirm=',
                '--dry-run',
                '--dump-aliases',
                '--envelope-sender=',
                '--force',
                '--from=',
                '--identity=',
                '--in-reply-to',
                '--in-reply-to=',
                '--no-signed-off-cc',
                '--no-suppress-from',
                '--quiet',
                '--smtp-auth=',
                '--smtp-debug=',
                '--smtp-domain=',
                '--smtp-encryption=',
                '--smtp-pass',
                '--smtp-server-option=',
                '--smtp-server-port=',
                '--smtp-server=',
                '--smtp-ssl',
                '--smtp-ssl-cert-path',
                '--smtp-user=',
                '--subject=',
                '--suppress-cc=',
                '--to-cmd=',
                '--to=',
                '--transfer-encoding=',
                '--xmailer'},
 'send-pack': {'--all',
               '--atomic',
               '--dry-run',
               '--exec=',
               '--force',
               '--receive-pack=',
               '--stdin',
               '--thin',
               '--verbose'},
 'sh-i18n': set(),
 'sh-i18n--envsubst': set(),
 'sh-setup': set(),
 'shell': set(),
 'shortlog': {'-w', '-s', '-e', '--format', '-n'},
 'show': {'--abbrev',
          '--abbrev-commit',
          '--binary',
          '--check',
          '--color',
          '--color-words',
          '--diff-algorithm=',
          '--diff-filter=',
          '--dirstat',
          '--dst-prefix=',
          '--encoding=',
          '--exit-code',
          '--ext-diff',
          '--find-copies-harder',
          '--full-index',
          '--histogram',
          '--ignore-blank-lines',
          '--ignore-space-at-eol',
          '--ignore-submodules',
          '--inter-hunk-context=',
          '--minimal',
          '--name-only',
          '--name-status',
          '--no-abbrev-commit',
          '--no-color',
          '--no-ext-diff',
          '--no-notes',
          '--no-prefix',
          '--no-renames',
          '--notes',
          '--numstat',
          '--oneline',
          '--patch-with-raw',
          '--patch-with-stat',
          '--patience',
          '--pickaxe-all',
          '--pickaxe-regex',
          '--pretty',
          '--raw',
          '--relative',
          '--shortstat',
          '--show-notes',
          '--show-signature',
          '--src-prefix=',
          '--stat',
          '--stat-name-width=',
          '--submodule',
          '--submodule=',
          '--summary',
          '--textconv',
          '--word-diff',
          '--word-diff-regex=',
          '--ws-error-highlight=',
          '-B',
          '-C',
          '-D',
          '-G',
          '-M',
          '-O',
          '-R',
          '-S',
          '-U',
          '-W',
          '-a',
          '-b',
          '-l',
          '-p',
          '-s',
          '-static',
          '-w',
          '-z'},
 'show-branch': {'--color',
                 '--current',
                 '--date-order',
                 '--independent',
                 '--list',
                 '--merge-base',
                 '--more=',
                 '--no-color',
                 '--no-name',
                 '--sha',
                 '--sparse',
                 '--topics',
                 '--topo-order',
                 '-a',
                 '-g',
                 '-r'},
 'show-index': set(),
 'show-ref': {'--abbrev',
              '--exclude-existing',
              '--hash=',
              '--head',
              '--tags',
              '--verify',
              '-d',
              '-q',
              '-s'},
 'st': {'--column',
        '--ignore-submodules',
        '--ignored',
        '--long',
        '--porcelain',
        '--split-index',
        '-b',
        '-s',
        '-u',
        '-v',
        '-z'},
 'stage': set(),
 'stash': {'-----H----I', '--patch', '--all'},
 'status': {'--column',
            '--ignore-submodules',
            '--ignored',
            '--long',
            '--porcelain',
            '--split-index',
            '-b',
            '-s',
            '-u',
            '-v',
            '-z'},
 'stripspace': {'-s', '-c'},
 'submodule': {'--cached',
               '--checkout',
               '--depth',
               '--files',
               '--force',
               '--init',
               '--merge',
               '--name',
               '--rebase',
               '--recursive',
               '--reference',
               '--remote',
               '-N',
               '-b',
               '-f',
               '-n',
               '-q'},
 'submodule--helper': set(),
 'subtree': set(),
 'svn': {'--add-author-from',
         '--authors-prog=',
         '--branches',
         '--commit-url',
         '--follow-parent',
         '--git-format',
         '--ignore-paths',
         '--ignore-paths=',
         '--include-paths=',
         '--incremental',
         '--interactive',
         '--limit=',
         '--localtime',
         '--log-window-size=',
         '--mergeinfo=',
         '--no-metadata',
         '--no-minimize-url',
         '--no-rebase',
         '--oneline',
         '--parent',
         '--parents',
         '--placeholder-filename=',
         '--prefix=',
         '--preserve-empty-dirs',
         '--rewrite-root=',
         '--rewrite-uuid=',
         '--rmdir',
         '--shared',
         '--show-commit',
         '--use-log-author',
         '--use-svm-props',
         '--use-svnsync-props',
         '--username',
         '--username=',
         '-A',
         '-B',
         '-R',
         '-T',
         '-b',
         '-d',
         '-e',
         '-i',
         '-l',
         '-m',
         '-n',
         '-p',
         '-q',
         '-r',
         '-t',
         '-v'},
 'symbolic-ref': {'--short', '-m', '-d', '-q'},
 'tag': {'--cleanup=',
         '--column',
         '--contains',
         '--create-reflog',
         '--points-at',
         '--sort=',
         '-F',
         '-a',
         '-d',
         '-f',
         '-l',
         '-m',
         '-n',
         '-s',
         '-u',
         '-v'},
 'unpack-file': set(),
 'unpack-objects': {'--strict', '-r', '-q', '-n'},
 'update-index': {'--add',
                  '--cacheinfo',
                  '--chmod=',
                  '--force-remove',
                  '--force-untracked-cache',
                  '--ignore-missing',
                  '--ignore-submodules',
                  '--index-info',
                  '--index-version',
                  '--info-only',
                  '--no-assume-unchanged',
                  '--really-refresh',
                  '--refresh',
                  '--remove',
                  '--replace',
                  '--split-index',
                  '--stdin',
                  '--unmerged',
                  '--unresolve',
                  '--untracked-cache',
                  '--verbose',
                  '-g',
                  '-q',
                  '-z'},
 'update-ref': set(),
 'update-server-info': {'-f'},
 'upload-archive': {'--remote'},
 'upload-pack': {'--timeout=', '--strict'},
 'var': {'-l'},
 'verify-commit': {'--raw', '-v'},
 'verify-pack': {'-s', '--verbose', '-v'},
 'verify-tag': {'--raw', '-v'},
 'web--browse': {'-b', '-t', '-c', '--config'},
 'whatchanged': set(),
 'worktree': {'-b', '-f', '-v', '--expire', '--detach', '--porcelain', '-n'},
 'write-tree': {'--prefix=', '--missing-ok'},
}

GIT_DASHES = [
    '--version', '--help', '-C', '-cname=', '--exec-path', '--html-path',
    '--man-path', '--info-path', '-p', '--no-replace-objects', '--bare',
    '--git-dir=', '--work-tree=', '--namespace=',
]

GIT_SUBCOMMAND_SUBCOMMANDS = {
    'remote': [
        'rename', 'get-url', 'set-url', 'remove', 'set-head', 'set-branches',
        'prune', 'add',
    ],
}
