update:
	mkdir -pv ~/.config/cicada/completers
	cp -rv ./completers/* ~/.config/cicada/completers/
	ln -sf ~/.config/cicada/completers/kubectl.yaml ~/.config/cicada/completers/k.yaml
	cp -v ./cicadarc ~/.config/cicada/cicadarc
