update:
	mkdir -pv ~/.config/cicada/completers
	cp -v ./cicadarc ~/.config/cicada/cicadarc
	cp -rv ./completers/* ~/.config/cicada/completers/
	ln -sf ~/.config/cicada/completers/kubectl.yaml ~/.config/cicada/completers/k.yaml
	ln -sf ~/.config/cicada/completers/docker.yaml ~/.config/cicada/completers/d.yaml
	ln -sf ~/.config/cicada/completers/git.yaml ~/.config/cicada/completers/g.yaml
